version: "3.8"

services:
  web:
    container_name: web-flask
    command: "gunicorn app.app:app --bind 0.0.0.0:8686 --reload"
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./src:/app
    expose:
      - "8686"

  postgres:
    image: postgres:13.2-alpine
    container_name: web-postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  nginx:
    image: nginx:stable-alpine
    container_name: web-nginx
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8686:8686"
    depends_on:
      - web