version: '3.8'

services:

  flaskwb:
    build: .
    container_name: flaskweb
    command: "gunicorn run:app --bind 0.0.0.0:8000 --reload"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./src:/app
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:stable-alpine
    container_name: nginxflask
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - flaskwb

  
  db:
    image: postgres:13
    container_name: postgresflask
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres-flask:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $POSTGRES_USER
      interval: 2s
      timeout: 3s
      retries: 40
    
volumes:
  postgres-flask:
    external: true



    

