# Generated by Django 3.2.13 on 2022-04-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_banco', models.IntegerField()),
                ('endereco', models.CharField(max_length=250)),
                ('fone', models.BigIntegerField()),
                ('tipo', models.IntegerField()),
                ('fone1', models.BigIntegerField(blank=True)),
                ('tipo1', models.IntegerField(blank=True)),
                ('agencia', models.CharField(max_length=250)),
                ('nome_agencia', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=250)),
                ('numero', models.CharField(max_length=250)),
            ],
        ),
    ]
